name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Checkout.com.sln
    - name: Build
      run: dotnet build Checkout.com.sln --no-restore
    - name: Test
      run: dotnet test Checkout.com.sln --no-build --verbosity normal
    - name: Docker build api
      run: |
        docker build ./ -t checkoutapi
    - name: Docker build simulator
      run: |
        docker build ./Checkout.com.BankSimulator -t checkoutsimulator
        
